import React from 'react';
import katex from 'katex';
import { AlertCircle, Lightbulb, Sparkles, Bookmark, Table as TableIcon } from 'lucide-react';

interface LatexRendererProps {
  content: string;
  className?: string;
  inline?: boolean;
  color?: string;
}

interface MathToken {
  id: string;
  formula: string;
  displayMode: boolean;
}

/**
 * Universal Subscript & Scientific Normalizer for Physics, Chemistry & Biology.
 * 
 * Guarantees that numbers and descriptive labels appear BELOW the letter as subscripts:
 * 1. Chemistry & Biology formulas:
 *    - C6H12O6 -> \text{C}_6\text{H}_{12}\text{O}_6
 *    - 6O2 -> 6\text{O}_2
 *    - 6CO2 -> 6\text{CO}_2
 *    - 6H2O -> 6\text{H}_2\text{O}
 *    - H2SO4, CaCO3, NH3, CH4, N2, Cl2, FADH2, etc.
 * 
 * 2. Physics & Chemistry variables:
 *    - mbullet, vbullet, mgun, vgun, vrecoil -> m_{\text{bullet}}, v_{\text{gun}}, etc.
 *    - v1, v2, m1, m2, t1, t2, r1, r2, p1, p2, F1, F2 -> v_1, v_2, m_1, m_2, etc.
 *    - Kc, Kp, Ksp, Kw, Ka, Kb -> K_c, K_p, K_{\text{sp}}, etc.
 * 
 * 3. Units & Reaction arrows:
 *    - textm/s, textkg -> \text{ m/s}, \text{ kg}
 *    - -> or --> -> \rightarrow
 */
/**
 * Rigorously balances curly braces { and } in LaTeX formulas.
 * Drops stray unmatched closing braces '}' anywhere in the formula,
 * and appends any missing closing braces at the end.
 */
function balanceBraces(str: string): string {
  let depth = 0;
  let out = '';
  for (let i = 0; i < str.length; i++) {
    const ch = str[i];
    // Check if backslash escaped \{ or \}
    if (ch === '\\' && i + 1 < str.length && (str[i + 1] === '{' || str[i + 1] === '}')) {
      out += ch + str[i + 1];
      i++;
      continue;
    }
    if (ch === '{') {
      depth++;
      out += ch;
    } else if (ch === '}') {
      if (depth > 0) {
        depth--;
        out += ch;
      }
      // If depth === 0, this is a stray closing brace like in {E_{n}-E_{(0)} }} or {r^6}}}}!
      // We safely omit it!
    } else {
      out += ch;
    }
  }
  if (depth > 0) {
    out += '}'.repeat(depth);
  }
  return out;
}

/**
 * Fixes operators accidentally trapped inside \text{...} or subscripts:
 * e.g. U_{\text{disp}\propto} \frac{\alpha^2 I}{r^6} -> U_{\text{disp}} \propto \frac{\alpha^2 I}{r^6}
 * e.g. U_{disp \propto \frac...} -> U_{\text{disp}} \propto \frac...
 */
function fixMisplacedSubscriptOperators(f: string): string {
  // 0. Clean trailing comma or punctuation directly before closing braces: e.g. ", }}" -> "}}"
  let s = f.replace(/,\s*(\}+)/g, '$1');

  // 1. If an operator is inside \text{...} like \text{disp}\propto} or \text{disp \propto}
  s = s.replace(/\\text\{([^{}]*?)(\\propto|=|\\approx|\\sim|<|>|\\leq|\\geq|\\le|\\ge|\\pm|\\times)(.*?)\}/g, (_, before, op, after) => {
    const cleanBefore = before.trim() ? `\\text{${before.trim()}}` : '';
    const cleanAfter = after.trim() ? `\\text{${after.trim()}}` : '';
    return `${cleanBefore} ${op} ${cleanAfter}`.trim();
  });

  // 2. If a subscript opens and immediately has an operator: e.g. a_{c=\dfrac...} -> a_c = \dfrac...
  // or a_{t=dv/dt} -> a_t = dv/dt
  // or U_{disp \propto \frac...} -> U_{\text{disp}} \propto \frac...
  // or U_{\text{disp}\propto} -> U_{\text{disp}} \propto
  s = s.replace(/_\{([a-zA-Z]{1,6}|\\text\{[^{}]+\})\s*(\\propto|=|\\approx|\\sim|<|>|\\leq|\\geq|\\le|\\ge)\s*/g, (_, label, op) => {
    const cleanLabel = label.startsWith('\\text{') ? label : label.length > 2 ? `\\text{${label}}` : label;
    return `_{${cleanLabel}} ${op} `;
  });

  // 3. Format standalone derivative fractions cleanly: dv/dt -> \dfrac{dv}{dt}
  s = s.replace(/\b(d[a-zA-Z\\]+)\/(dt)\b/g, '\\dfrac{$1}{$2}');

  return s;
}

/**
 * Repairs malformed or scrambled LaTeX syntax generated by LLMs:
 * - Fixes nested \text{\text{...}} -> \text{...}
 * - Fixes scrambled \text{ (\text{C}_{1}-}\text{OH}) -> (\text{C}_1\text{-OH})
 * - Balances mismatched curly braces
 */
function repairLatexFormula(f: string): string {
  let rep = f;

  // 0a. Replace bracket row-spacers in LaTeX line breaks: e.g. \\[4pt], \\[6pt] -> \\
  // KaTeX parses \\[4pt] as a line break followed by an undefined command \[4pt]!
  rep = rep.replace(/\\{1,2}\[[^\]\n]*\]/g, '\\\\');

  // 0b. Replace Unicode subscripts like ₍gun₎, ₍1₎, ₍initial₎ -> _{\text{gun}} or _{1}
  rep = rep.replace(/₍([a-zA-Z0-9]+)₎/g, (_, sub) => {
    return isNaN(Number(sub)) ? `_{\\text{${sub}}}` : `_{${sub}}`;
  });

  // 0c. Replace Unicode math symbols with LaTeX equivalents
  rep = rep.replace(/[·•]/g, ' \\cdot ');
  rep = rep.replace(/×/g, ' \\times ');
  rep = rep.replace(/÷/g, ' \\div ');
  rep = rep.replace(/≠/g, ' \\neq ');
  rep = rep.replace(/≈/g, ' \\approx ');
  rep = rep.replace(/≤/g, ' \\leq ');
  rep = rep.replace(/≥/g, ' \\geq ');
  rep = rep.replace(/±/g, ' \\pm ');
  rep = rep.replace(/°/g, '^{\\circ}');

  // 0d. Clean units like \ kg or \ m/s -> \text{ kg}, \text{ m/s}
  rep = rep.replace(/\\\s+([a-zA-Z]{1,4}(?:\/[a-zA-Z]{1,4})?)\b/g, '\\text{ $1}');

  // 1. Unnest any multiple \text{\text{...}}
  for (let k = 0; k < 6; k++) {
    rep = rep.replace(/\\text\{\s*\\text\{([^{}]+)\}\s*\}/g, '\\text{$1}');
  }

  // 2. Fix misplaced operators inside \text or subscripts
  rep = fixMisplacedSubscriptOperators(rep);

  // 3. Fix scrambled nested text cutoffs like:
  // \text{\text{Glucose}} \text{ (\text{C}_{1}-}\text{OH})
  rep = rep.replace(/\\text\{\s*\(?\\text\{([A-Za-z0-9]+)\}_\{?(\d+)\}?-?\s*\}\s*\\text\{([^{}]+)\}\)?/g, '($1_{$2}\\text{-$3})');
  rep = rep.replace(/\\text\{\s*\(?\\text\{([A-Za-z0-9]+)\}_\{?(\d+)\}?-?\s*\}/g, '($1_{$2}-');

  // Fix isolated \text{ (C_1-OH)} or \text{ (C_1-}
  rep = rep.replace(/\\text\{\s*\(([^)]+)\)\s*\}/g, '(\\text{$1})');

  // 4. Clean up stray leading double subscript mark: _{_1} -> _{1}
  rep = rep.replace(/_\{_(\d+)\}/g, '_{$1}');

  // 5. Rigorous curly braces balance (drops stray unmatched closing braces while preserving valid nested braces)
  rep = balanceBraces(rep);

  return rep;
}

/**
 * Universal Subscript & Scientific Normalizer for Physics, Chemistry & Biology.
 * 
 * Safely normalizes formulas WITHOUT corrupting existing \text{...} blocks:
 * 1. Chemistry & Biology formulas:
 *    - C6H12O6 -> C_{6}H_{12}O_{6}
 *    - 6O2 -> 6O_{2}
 *    - 6CO2 -> 6CO_{2}
 *    - 6H2O -> 6H_{2}O
 *    - H2SO4, CaCO3, NH3, CH4, N2, Cl2, FADH2, etc.
 * 
 * 2. Physics & Chemistry variables:
 *    - mbullet, vbullet, mgun, vgun, vrecoil -> m_{\text{bullet}}, v_{\text{gun}}, etc.
 *    - v1, v2, m1, m2, t1, t2, r1, r2, p1, p2, F1, F2 -> v_1, v_2, m_1, m_2, etc.
 *    - Kc, Kp, Ksp, Kw, Ka, Kb -> K_c, K_p, K_{\text{sp}}, etc.
 * 
 * 3. Units & Reaction arrows:
 *    - textm/s, textkg -> \text{ m/s}, \text{ kg}
 *    - -> or --> -> \rightarrow
 */
function normalizeMathFormula(rawFormula: string): string {
  let f = rawFormula;

  f = f.replace(/\t(imes|heta|an|au)/g, '\\t$1');
  f = f.replace(/\\?times\b/g, '\\times ');
  f = f.replace(/\s*(-->|->)\s*/g, ' \\rightarrow ');

  // PREVENT KATEX CRASHES: Force convert all broken units (\kg, \m/s, etc) into \text{...}
  f = f.replace(/\\{1,2}\s*(kg|m\/s|m|s|J|N|W|Hz|mol|kPa|atm|cm|mm|V|A|C|K|rad)\b/gi, '\\text{ $1}');

  for (let k = 0; k < 3; k++) {
    f = f.replace(/\\text\{\s*\\text\{([^{}]+)\}\s*\}/g, '\\text{$1}');
  }

  const textPlaceholders: string[] = [];
  f = f.replace(/\\text\{([^{}]*)\}/g, (_, inner) => {
    const placeholder = `%%%PROTECTED_TXT_${textPlaceholders.length}%%%`;
    textPlaceholders.push(`\\text{${inner}}`);
    return placeholder;
  });

  const commonPhysicsSubscripts = [
    'bullet', 'gun', 'recoil', 'initial', 'final', 'target', 
    'total', 'sys', 'net', 'max', 'min', 'avg', 'lost', 'gain',
    'eff', 'ext', 'int', 'in', 'out'
  ];

  for (const sub of commonPhysicsSubscripts) {
    const pattern = new RegExp(`\\b([mvPFEakWT])(?:_\\{?|_?|\\{)?(${sub})\\}?\\b`, 'g');
    f = f.replace(pattern, `$1_{\\text{${sub}}}`);
  }

  f = f.replace(/\b([a-zA-Z])_([a-zA-Z]{2,})\b/g, '$1_{\\text{$2}}');
  f = f.replace(/\b([vmprtFakqIs])(\d+)\b/g, '$1_{$2}');
  f = f.replace(/\bK(c|p|w|a|b)\b/g, 'K_$1');
  f = f.replace(/\bKsp\b/gi, 'K_{\\text{sp}}');

  f = f.replace(/\\(long)?mapsto\b/g, ' \\implies ');
  f = f.replace(/\\(models|vDash|vdash|Vdash)\b/g, ' = ');
  f = f.replace(/\\(mid|vert)\b/g, ' ');

  f = f.replace(/(=|\+|-|\*|\/|\\rightarrow|\\longrightarrow|\\implies|\\Longrightarrow|\\iff|\\Longleftrightarrow|\\times|\\pm|<|>|\\leq|\\geq)\s*\|+\s*/g, '$1 ');
  f = f.replace(/\s*\|+\s*(=|\+|-|\*|\/|\\rightarrow|\\longrightarrow|\\implies|\\Longrightarrow|\\iff|\\Longleftrightarrow|\\times|\\pm|<|>|\\leq|\\geq)/g, ' $1');

  f = f.replace(/=\s*\|+\s*-/g, '= -');
  f = f.replace(/=\s*\|+/g, '= ');
  f = f.replace(/\|+[\s=]*-/g, '- ');
  f = f.replace(/\|\s*(=>|->|==|=)/g, ' \\implies ');

  f = f.replace(/(?<=\s)\|(?=\s)/g, ' ');
  f = f.replace(/(?<![\\_a-zA-Z])([A-Z][a-z]?)(\d+)(?![_}])/g, '$1_{$2}');

  const wordsToWrap = ['Energy', 'ATP', 'ADP', 'Glucose', 'Maltose', 'Sucrose', 'Fructose', 'Galactose', 'Lactose'];
  for (const w of wordsToWrap) {
    const wordPattern = new RegExp(`\\b${w}\\b`, 'g');
    f = f.replace(wordPattern, `\\text{${w}}`);
  }

  textPlaceholders.forEach((origText, idx) => {
    f = f.replace(`%%%PROTECTED_TXT_${idx}%%%`, origText);
  });

  f = f.replace(/\\frac\b/g, '\\dfrac');
  f = repairLatexFormula(f);

  return f;
}

/**
 * Normalizes all AI model math conventions (GPT-4o, GPT-OSS 120b, DeepSeek, Qwen, Claude, Gemini)
 * into a single unified token pipeline.
 */
function normalizeAiDelimiters(text: string): string {
  // 0. Normalize all newline representations
  let s = text.replace(/\r\n/g, '\n').replace(/\\r\\n/g, '\n').replace(/\\n/g, '\n');

  // 0.5. CRITICAL FIX: Strip hallucinated \text{ \begin{aligned}... } wrappers that cause KaTeX to render raw code
  s = s.replace(/\\text\{\s*\\begin\{(aligned|gathered|cases|matrix|pmatrix|bmatrix|vmatrix|split|eqnarray\*?|equation\*?|align\*?|gather\*?|multline\*?)\}([\s\S]*?)\\end\{\1\}\s*\}/gi, '\\begin{$1}$2\\end{$1}');

  // 1. Convert markdown code blocks with latex/math tags into block math
  s = s.replace(/```(?:latex|math|tex)\s*([\s\S]*?)\s*```/gi, '\n\n$$$$$1$$$$\n\n');

  // 2. Convert LaTeX display math \[ ... \] into $$...$$
  s = s.replace(/(?:\\{1,2}\[)([\s\S]*?)(?:\\{1,2}\])/g, '\n\n$$$$$1$$$$\n\n');

  // 3. Convert LaTeX inline math \( ... \) into $...$
  s = s.replace(/(?:\\{1,2}\()([\s\S]*?)(?:\\{1,2}\))/g, '$$$1$$');

  // Placeholder system to safely protect valid math blocks from being double-wrapped or fragmented
  const tempBlocks: string[] = [];
  const hideMath = (str: string) => {
    let res = str.replace(/\$\$([\s\S]*?)\$\$/g, (_, inner) => {
      // Auto-convert environments that cause KaTeX errors in $$...$$ to aligned
      const fixedInner = inner.replace(/\\begin\{(eqnarray\*?|equation\*?|align\*?|gather\*?|multline\*?)\}([\s\S]*?)\\end\{\1\}/gi, '\\begin{aligned}$2\\end{aligned}');
      tempBlocks.push(`$$${fixedInner}$$`);
      return `%%%TEMP_MATH_BLOCK_${tempBlocks.length - 1}%%%`;
    });
    res = res.replace(/\$([^\$\n\r]+?)\$/g, (match) => {
      tempBlocks.push(match);
      return `%%%TEMP_MATH_BLOCK_${tempBlocks.length - 1}%%%`;
    });
    return res;
  };

  // 4. Hide all correctly formatted math blocks
  s = hideMath(s);

  // 5. Safely wrap bare LaTeX environments into display math $$...$$
  s = s.replace(/\\begin\{(aligned|gathered|cases|matrix|pmatrix|bmatrix|vmatrix|split|eqnarray\*?|equation\*?|align\*?|gather\*?|multline\*?)\}([\s\S]*?)\\end\{\1\}/gi, (match, env, inner) => {
    if (/^(eqnarray\*?|equation\*?|align\*?|gather\*?|multline\*?)$/i.test(env)) {
      return `\n\n$$\n\\begin{aligned}${inner}\\end{aligned}\n$$\n\n`;
    }
    return `\n\n$$\n\\begin{${env}}${inner}\\end{${env}}\n$$\n\n`;
  });

  // 6. Hide newly wrapped environments before running line-by-line bare math scans
  s = hideMath(s);

  // 7. Clean isolated standalone [ or ]
  s = s.replace(/^\s*\\{1,2}\[\s*$/gm, '');
  s = s.replace(/^\s*\\{1,2}\]\s*$/gm, '');

  // 8. Normalize double backslashes before common LaTeX math commands
  s = s.replace(/\\{2,}(circ|theta|alpha|beta|gamma|lambda|mu|pi|sigma|omega|Delta|Omega|times|pm|div|approx|neq|le|ge|leq|geq|frac|dfrac|sqrt|sin|cos|tan|Longrightarrow|longrightarrow|rightarrow|implies)\b/g, '\\$1');

  // 9. Auto-detect standalone bare LaTeX formula lines
  s = s.split('\n').map(line => {
    const trimmed = line.trim();
    if (!trimmed || /^[#*\\-`]/.test(trimmed) || trimmed.startsWith('|')) return line;
    
    // Skip lines that have been safely hidden inside placeholders
    if (/^%%%TEMP_MATH_BLOCK_\d+%%%$/.test(trimmed)) return line;

    const hasAdvancedMath = /\\(frac|dfrac|sqrt|sum|int|Longrightarrow|longrightarrow|rightarrow|implies|mapsto|text|over)\b/.test(trimmed);
    const hasMathSymbols = hasAdvancedMath || /\\(sin|cos|tan|cot|sec|csc|log|ln|alpha|beta|gamma|delta|theta|lambda|mu|pi|sigma|omega|Delta|Omega)\b|[_^]/.test(trimmed);
    const hasEqualsOrArrow = /[=<>≈∝≠≤≥]|\\leq|\\geq|\\propto|\\approx|\\Longrightarrow|\\longrightarrow|\\rightarrow|\\implies/.test(trimmed);
    const startsWithMath = /^([a-zA-Z0-9]+(?:_\{(?:[^{}]|\{[^{}]*\})+\}|_[a-zA-Z0-9]+|\^[a-zA-Z0-9]+)?\s*=|\\[a-zA-Z]+)/.test(trimmed);

    const hasProseWords = /\b(the|and|is|are|was|were|for|with|from|which|that|this|these|those|directed|toward|because|since|where|then|when|given|by|if|of|in|to|so|use|check|pair|angles|speed|projectile|launched|ground|horizontal|range|produce|same|equal|occurs|values|two|different|condition|relationship|solve|calculate|find|determine|mass|velocity|force|acceleration|energy|momentum|power|work|time|distance|displacement|equation|formula|solution|step)\b/i.test(trimmed);

    if (hasAdvancedMath && hasEqualsOrArrow && !hasProseWords) return `\n\n$$${trimmed}$$\n\n`;
    if (hasProseWords) return line;
    if ((hasMathSymbols && hasEqualsOrArrow) || (startsWithMath && (hasMathSymbols || hasEqualsOrArrow))) {
      return `\n\n$$${trimmed}$$\n\n`;
    }

    return line;
  }).join('\n');

  // 10. Hide newly wrapped standalone lines
  s = hideMath(s);

  // 11. Auto-detect inline math expressions embedded directly into English prose
  s = s.replace(/(?<![\$\w\\])((?:\\?[a-zA-Z0-9_\{\}\s\+\-\*\/=]+)?\\(?:Longrightarrow|longrightarrow|rightarrow|implies)(?:[^\$\n\r,.]+(?:,[^\$\n\r]+)?))(?!\$)/g, (_, m) => `$${m.trim()}$`);
  s = s.replace(/(?<![\$\w\\])((?:[a-zA-Z0-9_](?:_\{(?:[^{}]|\{[^{}]*\})+\}|_[a-zA-Z0-9]+)?\s*=\s*(?:[-+]\s*|\\,\s*|\\;\s*|\\:\s*)*)?\\(?:frac|dfrac)\s*\{[^{}\n]*\}\s*\{[^{}\n]*\}(?:\s*\\?[a-zA-Z0-9\\\,\;\^_{}\(\)\[\]]+)*)(?!\$)/g, (_, m) => `$${m.trim()}$`);
  s = s.replace(/(?<![\$\w\\])(\\[a-zA-Z]+(?:_\{(?:[^{}]|\{[^{}]*\})+\}|_[a-zA-Z0-9]+)?\s*[\+\-\*\/]\s*\\[a-zA-Z]+(?:_\{(?:[^{}]|\{[^{}]*\})+\}|_[a-zA-Z0-9]+)?\s*=\s*\d+(?:\^\s*\\*\{?\\*circ\}?)?)(?!\$)/g, (_, m) => `$${m}$`);
  s = s.replace(/(?<![\$\w\\])(\\?(?:sin|cos|tan|cot|sec|csc)\s*(?:\d+)?\s*\\[a-zA-Z]+(?:_\{(?:[^{}]|\{[^{}]*\})+\}|_[a-zA-Z0-9]+)?)(?!\$)/g, (_, m) => `$${m.startsWith('\\') ? m : '\\' + m}$`);
  s = s.replace(/(?<![\$\w\\])((?:[a-zA-Z]|\d+(?:\.\d+)?)\s*\^\s*\\*(?:\{?\\*circ\}?|o\b))(?!\$)/g, (_, m) => `$${m.replace(/\^\\*o\b/, '^{\\circ}').replace(/\^\s*\\*\{?\\*circ\}?/, '^{\\circ}')}$`);
  s = s.replace(/(?<![\$\w\\\{])(\d+(?:\.\d+)?\s*\^\s*(?:\{[-+]?\d+\}|[-+]?\d+))(?!\$)/g, (_, m) => `$${m}$`);
  s = s.replace(/(?<![\$\w\\])([a-zA-Z](?:_\{(?:[^{}]|\{[^{}]*\})+\}|_[a-zA-Z0-9]+)?\s*=\s*[-+]?\s*\d+(?:\.\d+)?(?:\s*\\text\{[^{}]+\}|\s*\\[a-zA-Z]+)?)(?!\$)/g, (_, m) => `$${m.trim()}$`);

  // 12. Unhide & restore all completely validated math blocks back into the text flow
  let iterations = 0;
  while (s.includes('%%%TEMP_MATH_BLOCK_') && iterations < 5) {
    s = s.replace(/%%%TEMP_MATH_BLOCK_(\d+)%%%/g, (_, idx) => tempBlocks[parseInt(idx, 10)]);
    iterations++;
  }

  // 13. Split unescaped '&' inside inline math blocks
  s = s.replace(/\$([^\$\n\r]+?)\$/g, (_, math) => {
    if (math.includes('&') && !math.includes('\\begin{')) {
      return math.split('&').map((p: string) => `$${p.trim()}$`).join(' & ');
    }
    return `$${math}$`;
  });

  return s;
}

function extractMathTokens(text: string): { processedText: string; tokens: Map<string, MathToken> } {
  const tokens = new Map<string, MathToken>();
  let tokenCounter = 0;

  let raw = normalizeAiDelimiters(text);

  let processedText = raw.replace(/\$\$([\s\S]*?)\$\$/g, (_, formula) => {
    if (!formula.trim()) return '';
    const tokenId = `%%%MATH_BLOCK_${tokenCounter++}%%%`;
    tokens.set(tokenId, {
      id: tokenId,
      formula: normalizeMathFormula(formula),
      displayMode: true
    });
    return `\n\n${tokenId}\n\n`;
  });

  processedText = processedText.replace(/\$([^\$\n\r]+?)\$/g, (_, formula) => {
    if (!formula.trim()) return '';
    const tokenId = `%%%MATH_INLINE_${tokenCounter++}%%%`;
    tokens.set(tokenId, {
      id: tokenId,
      formula: normalizeMathFormula(formula),
      displayMode: false
    });
    return tokenId;
  });

  processedText = processedText.replace(/(?<![\\\w%])([a-zA-Z](?:_\{(?:[^{}]|\{[^{}]*\})+\}|\^\{(?:[^{}]|\{[^{}]*\})+\}|_[a-zA-Z0-9]+|\^[a-zA-Z0-9]+))(?!\w)/g, (_, formula) => {
    const tokenId = `%%%MATH_INLINE_${tokenCounter++}%%%`;
    tokens.set(tokenId, {
      id: tokenId,
      formula: normalizeMathFormula(formula),
      displayMode: false
    });
    return tokenId;
  });

  processedText = processedText.replace(/(?<![\\\w%])(\\(?:alpha|beta|gamma|delta|epsilon|theta|lambda|mu|pi|sigma|tau|phi|omega|Delta|Omega)(?:_\{(?:[^{}]|\{[^{}]*\})+\}|\^\{(?:[^{}]|\{[^{}]*\})+\}|_[a-zA-Z0-9]+|\^[a-zA-Z0-9]+)?)(?![a-zA-Z])/g, (_, formula) => {
    const tokenId = `%%%MATH_INLINE_${tokenCounter++}%%%`;
    tokens.set(tokenId, {
      id: tokenId,
      formula: normalizeMathFormula(formula),
      displayMode: false
    });
    return tokenId;
  });

  return { processedText, tokens };
}

// High-performance LRU-like Map cache for rendered KaTeX HTML strings (up to 1200 entries)
const katexRenderCache = new Map<string, { html: string; hasError: boolean }>();
const MAX_KATEX_CACHE_SIZE = 1200;

function getCachedKatex(formula: string, displayMode: boolean): { html: string; hasError: boolean } {
  const cacheKey = `${displayMode ? 'D' : 'I'}::${formula}`;
  const existing = katexRenderCache.get(cacheKey);
  if (existing) return existing;

  let html = '';
  let hasError = false;

  try {
    html = katex.renderToString(formula, {
      displayMode,
      throwOnError: false,
    });
    if (html.includes('katex-error') || html.includes('color:#cc0000')) {
      hasError = true;
    }
  } catch {
    hasError = true;
  }

  // If initial render produced a KaTeX error, attempt multi-tiered repair passes
  if (hasError) {
    try {
      const repaired = repairLatexFormula(formula);
      html = katex.renderToString(repaired, {
        displayMode,
        throwOnError: false,
      });
      if (!html.includes('katex-error') && !html.includes('color:#cc0000')) {
        hasError = false;
      }
    } catch {
      hasError = true;
    }
  }

  // Tier 3: Try balancing braces and fixing subscript operators directly on the raw formula
  if (hasError) {
    try {
      const directHealed = balanceBraces(fixMisplacedSubscriptOperators(formula));
      html = katex.renderToString(directHealed, {
        displayMode,
        throwOnError: false,
      });
      if (!html.includes('katex-error') && !html.includes('color:#cc0000')) {
        hasError = false;
      }
    } catch {
      hasError = true;
    }
  }

  if (katexRenderCache.size >= MAX_KATEX_CACHE_SIZE) {
    const firstKey = katexRenderCache.keys().next().value;
    if (firstKey) katexRenderCache.delete(firstKey);
  }
  const result = { html, hasError };
  katexRenderCache.set(cacheKey, result);
  return result;
}

/**
 * Render a KaTeX math token safely to React Node.
 * Even if KaTeX catastrophically fails, this fallback ensures NO raw LaTeX tags leak to the UI.
 */
function renderMathToken(token: MathToken, key: string | number, color: string = 'text-cyan-300'): React.ReactNode {
  const formula = token.formula.trim();
  const { html, hasError } = getCachedKatex(formula, token.displayMode);

  // ULTIMATE FALLBACK: Strips environments, alignment tags, and gracefully maps to multiple lines
  if (hasError) {
    let cleanDisplay = formula
      .replace(/\\begin\{[a-zA-Z*]+\}/g, '')
      .replace(/\\end\{[a-zA-Z*]+\}/g, '')
      .replace(/\\text\{\s*\\text\{([^{}]+)\}\s*\}/g, '$1')
      .replace(/\\text\{([^{}]+)\}/g, '$1')
      .replace(/\\(rightarrow|longrightarrow|implies)/g, ' → ')
      .replace(/\\times/g, ' × ')
      .replace(/\\pm/g, ' ± ')
      .replace(/\\propto/g, ' ∝ ')
      .replace(/\\(approx|sim)/g, ' ≈ ')
      .replace(/\\(neq|ne)/g, ' ≠ ')
      .replace(/\\(leq|le)/g, ' ≤ ')
      .replace(/\\(geq|ge)/g, ' ≥ ')
      .replace(/\\cdot/g, ' · ')
      .replace(/\\sum/g, ' ∑ ')
      .replace(/\\int/g, ' ∫ ')
      .replace(/\\alpha/g, 'α')
      .replace(/\\beta/g, 'β')
      .replace(/\\gamma/g, 'γ')
      .replace(/\\delta/g, 'δ')
      .replace(/\\Delta/g, 'Δ')
      .replace(/\\theta/g, 'θ')
      .replace(/\\lambda/g, 'λ')
      .replace(/\\mu/g, 'μ')
      .replace(/\\pi/g, 'π')
      .replace(/\\sigma/g, 'σ')
      .replace(/\\omega/g, 'ω')
      .replace(/\\Omega/g, 'Ω')
      .replace(/\\langle/g, '⟨')
      .replace(/\\rangle/g, '⟩')
      .replace(/\\hat\{([^}]+)\}/g, '$1̂')
      .replace(/\\(dfrac|frac)\{([^{}]+)\}\{([^{}]+)\}/g, '($2 / $3)')
      .replace(/_\{([^{}]+)\}/g, '₍$1₎')
      .replace(/_([a-zA-Z0-9])/g, '₍$1₎')
      .replace(/\^\{([^}]+)\}/g, '⁽$1⁾')
      .replace(/\^([a-zA-Z0-9])/g, '⁽$1⁾')
      .replace(/\\,/g, ' ')
      .replace(/\\;/g, ' ')
      .replace(/\\:/g, ' ')
      .replace(/\\\s+/g, ' ')
      .replace(/&/g, '')
      .replace(/\\{1,2}/g, '\n'); // Convert LaTeX line breaks to visual line breaks

    const fallbackLines = cleanDisplay.split('\n').map(l => l.trim()).filter(Boolean);

    return (
      <span
        key={key}
        className={token.displayMode 
          ? `my-2 block text-center font-serif ${color} text-sm sm:text-base leading-normal select-text`
          : `inline-block px-1 font-serif ${color} align-baseline select-text`
        }
      >
        {fallbackLines.map((line, idx) => (
          <span key={idx} className={token.displayMode ? 'block my-0.5' : 'inline'}>{line}</span>
        ))}
      </span>
    );
  }

  if (token.displayMode) {
    return (
      <div
        key={key}
        className={`my-3 overflow-x-auto py-1 text-center font-serif ${color} text-sm sm:text-base leading-normal select-text`}
        dangerouslySetInnerHTML={{ __html: html }}
      />
    );
  }

  return (
    <span
      key={key}
      className={`inline-block px-0.5 font-serif ${color} align-middle select-text`}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

/**
 * Parses inline spans: Math Tokens, Bold, Italics, Code
 */
function parseInlineSpans(text: string, tokens: Map<string, MathToken>, color: string = 'text-cyan-300'): React.ReactNode[] {
  if (!text) return [];

  // Match:
  // 1. Math Tokens: %%%MATH_(BLOCK|INLINE)_\d+%%%
  // 2. Bold: **...**
  // 3. Inline Code: `...`
  // 4. Italic: *...*
  const tokenRegex = /(%%%MATH_(?:BLOCK|INLINE)_\d+%%%|\*\*[\s\S]*?\*\*|`[^`]+?`|\*[^\*]+?\*)/g;
  const parts = text.split(tokenRegex);

  return parts.map((part, index) => {
    if (!part) return null;

    // Check if it's a math token
    if (tokens.has(part)) {
      return renderMathToken(tokens.get(part)!, `math_${index}`, color);
    }

    // Safety fallback: Never show raw placeholder token to student
    if (/^%%%MATH_(?:BLOCK|INLINE)_\d+%%%$/.test(part)) {
      return null;
    }

    // Bold: **...**
    if (part.startsWith('**') && part.endsWith('**') && part.length >= 4) {
      const inner = part.slice(2, -2);
      return (
        <strong key={`b_${index}`} className="font-bold text-white">
          {parseInlineSpans(inner, tokens, color)}
        </strong>
      );
    }

    // Inline Code: `...`
    if (part.startsWith('`') && part.endsWith('`') && part.length > 2) {
      return (
        <code
          key={`code_${index}`}
          className="mx-0.5 rounded bg-slate-800 px-1.5 py-0.5 font-mono text-[11px] text-cyan-300 border border-slate-700/60"
        >
          {part.slice(1, -1)}
        </code>
      );
    }

    // Italic: *...*
    if (part.startsWith('*') && part.endsWith('*') && part.length > 2 && !part.startsWith('**')) {
      const inner = part.slice(1, -1);
      return (
        <em key={`em_${index}`} className="italic text-slate-300">
          {parseInlineSpans(inner, tokens, color)}
        </em>
      );
    }

    // Standalone times or multiplication symbol
    if (part.trim() === '\\times') {
      return ' × ';
    }

    return part;
  });
}

/**
 * Parses a markdown table row into trimmed cell strings
 */
function parseTableRow(line: string): string[] {
  const trimmed = line.trim();
  const rawCells = trimmed.split('|');
  // Strip outer empty strings from leading/trailing pipes
  if (rawCells.length > 0 && rawCells[0].trim() === '') rawCells.shift();
  if (rawCells.length > 0 && rawCells[rawCells.length - 1].trim() === '') rawCells.pop();
  return rawCells.map(c => c.trim());
}

/**
 * Checks if a line is a markdown table separator (e.g. |:---|:---|:---| or |---|---| or :---|---:)
 */
function isTableSeparator(line: string): boolean {
  const trimmed = line.trim();
  if (!trimmed.includes('-')) return false;
  if (!trimmed.includes('|')) return false;
  const cells = parseTableRow(trimmed);
  return cells.length > 0 && cells.every(c => /^:?-+:?$/.test(c.trim()));
}

/**
 * Checks if a line resembles a markdown table row (has at least 1 pipe and not just a single lonely pipe)
 */
function isPotentialTableRow(line: string): boolean {
  const trimmed = line.trim();
  if (trimmed === '|' || trimmed === '||') return false;
  const pipeCount = (trimmed.match(/\|/g) || []).length;
  return pipeCount >= 1 && (trimmed.startsWith('|') || trimmed.endsWith('|') || pipeCount >= 2);
}

/**
 * Renders a complete Markdown table with responsive horizontal scroll and Tailwind styling
 */
function renderMarkdownTable(
  headerLine: string,
  bodyLines: string[],
  keyPrefix: string,
  tokens: Map<string, MathToken>,
  color: string = 'text-cyan-300'
): React.ReactNode {
  let headers = parseTableRow(headerLine);
  let rows = bodyLines.map(parseTableRow);

  // Compute maximum columns across all rows to prevent layout breakage
  const maxCols = Math.max(headers.length, ...rows.map(r => r.length), 1);

  // Auto-pad headers if body has more columns (e.g. numbered index column without header)
  if (headers.length < maxCols) {
    if (rows.length > 0 && rows.every(r => /^\d+$/.test(r[0]?.trim() || ''))) {
      headers = ['#', ...headers];
    }
    while (headers.length < maxCols) {
      headers.push(`Column ${headers.length + 1}`);
    }
  }

  // Auto-pad rows if any row has fewer cells
  rows = rows.map(r => {
    const padded = [...r];
    while (padded.length < headers.length) {
      padded.push('');
    }
    return padded;
  });

  return (
    <div key={keyPrefix} className="my-3 overflow-x-auto rounded-xl border border-slate-700/80 bg-slate-900/95 shadow-lg no-scrollbar">
      <table className="w-full text-left text-xs sm:text-sm border-collapse min-w-[340px]">
        <thead>
          <tr className="bg-slate-800/90 text-cyan-300 font-semibold border-b border-slate-700/80">
            {headers.map((h, hIdx) => (
              <th key={hIdx} className="px-3.5 py-2.5 font-bold tracking-wide text-cyan-200 uppercase text-[11px] sm:text-xs">
                {parseInlineSpans(h, tokens, color)}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-800/80">
          {rows.map((rowCells, rIdx) => (
            <tr
              key={rIdx}
              className={rIdx % 2 === 0 ? 'bg-slate-900/40 hover:bg-slate-800/40 transition-colors' : 'bg-slate-800/20 hover:bg-slate-800/40 transition-colors'}
            >
              {rowCells.map((cell, cIdx) => (
                <td key={cIdx} className="px-3.5 py-2 text-slate-200 leading-relaxed">
                  {parseInlineSpans(cell, tokens, color)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

/**
 * Cleans markdown anomalies like dangling asterisks, clumped headers, etc.
 */
function cleanMarkdownText(text: string): string {
  let cleaned = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n');

  // 1. Remove lonely pipes, hashes, or dangling bullet markers on their own lines
  cleaned = cleaned.replace(/^\s*\|+\s*$/gm, '');
  cleaned = cleaned.replace(/^\s*#{1,6}\s*$/gm, '');
  cleaned = cleaned.replace(/^\s*[*•\-]\s*$/gm, '');

  // 2. Separate horizontal rules stuck to headings (e.g. "--- ### 2.")
  cleaned = cleaned.replace(/---\s*(#{1,6})/g, '\n---\n\n$1');

  // 3. Separate inline headings clumped into text (e.g. "bullet. --- ### 2.")
  cleaned = cleaned.replace(/([^\n])\s*(#{1,6}\s+)/g, '$1\n\n$2');

  // 4. Clean trailing or broken asterisks like "40 kg **." or "platform mass of 40 kg **"
  cleaned = cleaned.replace(/\s+\*\*\s*([.,;!?]|$)/gm, '$1');

  // 5. Clean broken word bolding like "M*over" -> "**M**over"
  cleaned = cleaned.replace(/M\*over/g, '**M**over');

  // 6. Break up run-on numbered items like: "1. Direction Matters: ... 2. Unit Consistency:"
  cleaned = cleaned.replace(/([.!?])\s+(\d+\.\s+[A-Z])/g, '$1\n\n$2');

  return cleaned;
}

/**
 * Renders an array of content lines into React blocks (Tables, Headings, Callouts, Lists, Paragraphs)
 */
function renderContentLines(
  lines: string[],
  keyPrefix: string,
  tokens: Map<string, MathToken>,
  insideCallout = false,
  color: string = 'text-cyan-300'
): React.ReactNode[] {
  const blocks: React.ReactNode[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!trimmed) {
      i++;
      continue;
    }

    // 1. Standalone Math Block Token
    if (tokens.has(trimmed) && tokens.get(trimmed)!.displayMode) {
      blocks.push(renderMathToken(tokens.get(trimmed)!, `${keyPrefix}_math_${i}`, color));
      i++;
      continue;
    }

    // 2. Horizontal divider
    if (trimmed === '---' || trimmed === '***' || trimmed === '___') {
      blocks.push(
        <hr key={`${keyPrefix}_hr_${i}`} className="my-3 border-slate-800" />
      );
      i++;
      continue;
    }

    // 3. Markdown Table Detection
    // A table begins when line has '|' (or is a potential row) and the next line is a valid table separator
    if (isPotentialTableRow(trimmed) && i + 1 < lines.length) {
      const nextLine = lines[i + 1].trim();
      if (isTableSeparator(nextLine)) {
        const headerLine = trimmed;
        const tableBodyLines: string[] = [];
        i += 2; // skip header and separator
        while (i < lines.length && isPotentialTableRow(lines[i])) {
          tableBodyLines.push(lines[i].trim());
          i++;
        }
        blocks.push(renderMarkdownTable(headerLine, tableBodyLines, `${keyPrefix}_tbl_${i}`, tokens, color));
        continue;
      }
    }

    // 4. Callout Section Detection (Only top-level, prevent infinite recursion)
    if (!insideCallout) {
      // Must explicitly be a Mnemonic, Exam Insight, Trap, or Caution block (with unicode flags so greetings like 👋 or 📚 are never matched)
      const isCalloutHeader = 
        /^(#{1,6}\s*)?(?:🚨|💡|⚠️|📌)\s*\*{0,2}(Mnemonic|FBISE Exam Insight|Exam Insight|Caution|Important Tip|Crucial Tip|Common Trap|Tip|Warning|Summary)/iu.test(trimmed) ||
        /^(#{1,6}\s*)?\*{1,2}(Mnemonic|FBISE Exam Insight|Exam Insight|Crucial Tip|Common Trap|Caution|Warning)/i.test(trimmed);

      if (isCalloutHeader) {
        const isAlert = /(?:🚨|⚠️|Exam Insight|Trap|Caution|Warning)/iu.test(trimmed);
        
        let title = trimmed
          .replace(/^(#{1,6}\s*)/, '')
          .replace(/(?:🚨|💡|⚠️|📌|❖|◆)/gu, '')
          .replace(/\*\*/g, '')
          .replace(/:+$/, '')
          .trim();

        if (!title) {
          title = isAlert ? 'FBISE Exam Insight' : 'Mnemonic & Summary';
        }

        // Collect body lines until next heading or divider
        const calloutBodyLines: string[] = [];
        i++;
        while (i < lines.length) {
          const nextTrimmed = lines[i].trim();
          if (
            nextTrimmed.startsWith('#') || 
            nextTrimmed === '---' || 
            /^(?:🚨|💡|⚠️|📌)\s*\*{0,2}(Mnemonic|FBISE|Exam|Caution|Trap)/iu.test(nextTrimmed)
          ) {
            break;
          }
          if (nextTrimmed) {
            calloutBodyLines.push(nextTrimmed);
          }
          i++;
        }

        blocks.push(
          <div
            key={`${keyPrefix}_callout_${i}`}
            className={`my-3 rounded-xl border p-3.5 shadow-lg ${
              isAlert
                ? 'border-rose-500/40 bg-gradient-to-br from-rose-950/40 via-slate-900 to-slate-950 text-slate-200'
                : 'border-amber-500/40 bg-gradient-to-br from-amber-950/40 via-slate-900 to-slate-950 text-slate-200'
            }`}
          >
            <div className="flex items-center gap-2 font-bold text-xs sm:text-sm mb-2">
              {isAlert ? (
                <AlertCircle className="h-4 w-4 text-rose-400 shrink-0" />
              ) : (
                <Lightbulb className="h-4 w-4 text-amber-400 shrink-0" />
              )}
              <span className={isAlert ? 'text-rose-300' : 'text-amber-300'}>
                {parseInlineSpans(title, tokens, color)}
              </span>
            </div>

            <div className="space-y-1.5 text-xs sm:text-sm leading-relaxed">
              {renderContentLines(calloutBodyLines, `${keyPrefix}_callout_inner_${i}`, tokens, true, color)}
            </div>
          </div>
        );
        continue;
      }
    }

    // 4.5. Skip stray markdown syntax markers on their own line
    if (/^#{1,6}\s*$/.test(trimmed) || /^[*•\-]\s*$/.test(trimmed) || /^\|+\s*$/.test(trimmed)) {
      i++;
      continue;
    }

    // 5. Headings: H1, H2, H3, H4
    if (trimmed.startsWith('#')) {
      const hashMatch = trimmed.match(/^(#{1,6})\s+(.*)$/);
      if (hashMatch && hashMatch[2].trim()) {
        const level = hashMatch[1].length;
        const text = hashMatch[2].trim();

        if (level === 1) {
          blocks.push(
            <h1 key={`${keyPrefix}_h1_${i}`} className="mt-4 mb-2 text-base sm:text-lg font-bold text-white border-b border-slate-800 pb-1.5">
              {parseInlineSpans(text, tokens, color)}
            </h1>
          );
        } else if (level === 2) {
          blocks.push(
            <h2 key={`${keyPrefix}_h2_${i}`} className="mt-3.5 mb-1.5 text-sm sm:text-base font-bold text-cyan-300 flex items-center gap-1.5">
              <Sparkles className="h-4 w-4 text-cyan-400 shrink-0" />
              <span>{parseInlineSpans(text, tokens, color)}</span>
            </h2>
          );
        } else if (level === 3) {
          blocks.push(
            <h3 key={`${keyPrefix}_h3_${i}`} className="mt-3 mb-1 text-xs sm:text-sm font-bold text-cyan-200 flex items-center gap-1.5">
              <Bookmark className="h-3.5 w-3.5 text-cyan-400 shrink-0" />
              <span>{parseInlineSpans(text, tokens, color)}</span>
            </h3>
          );
        } else {
          blocks.push(
            <h4 key={`${keyPrefix}_h4_${i}`} className="mt-2.5 mb-1 text-xs font-bold text-emerald-300 uppercase tracking-wide flex items-center gap-1">
              <span>{parseInlineSpans(text, tokens, color)}</span>
            </h4>
          );
        }
        i++;
        continue;
      } else {
        // Stray '#' or '##' with no header text: silently skip
        i++;
        continue;
      }
    }

    // 6. Numbered step or bullet items (e.g. "1.", "2.", "•", "*", "-")
    const listMatch = trimmed.match(/^(\*|-|•|\d+[\.\)])\s+(.*)$/);
    if (listMatch) {
      const marker = listMatch[1];
      const text = listMatch[2];
      const isNumbered = /^\d+/.test(marker);

      blocks.push(
        <div key={`${keyPrefix}_li_${i}`} className="my-1 flex items-start gap-2 pl-1 sm:pl-2 text-xs sm:text-sm text-slate-200">
          {isNumbered ? (
            <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-cyan-950 border border-cyan-500/40 text-[10px] font-bold text-cyan-300 mt-0.5">
              {marker.replace(/[\.\)]/, '')}
            </span>
          ) : (
            <span className="h-1.5 w-1.5 shrink-0 rounded-full bg-cyan-400 mt-2" />
          )}
          <div className="leading-relaxed flex-1">
            {parseInlineSpans(text, tokens, color)}
          </div>
        </div>
      );
      i++;
      continue;
    }

    // 7. Standard Paragraph
    blocks.push(
      <p key={`${keyPrefix}_p_${i}`} className="my-1 text-xs sm:text-sm text-slate-200 leading-relaxed">
        {parseInlineSpans(trimmed, tokens, color)}
      </p>
    );
    i++;
  }

  return blocks;
}

/**
 * Universal, Bulletproof Markdown + LaTeX Renderer
 */
export const LatexRenderer: React.FC<LatexRendererProps> = React.memo(({
  content,
  className = '',
  inline = false,
  color = 'text-cyan-300'
}) => {
  if (!content) return null;

  // Step 1: Tokenize all math formulas FIRST
  const { processedText: textWithTokens, tokens } = extractMathTokens(content);

  // If inline rendering requested, parse inline directly
  if (inline) {
    return <span className={className}>{parseInlineSpans(textWithTokens, tokens, color)}</span>;
  }

  // Step 2: Clean markdown text while preserving math tokens
  const cleanedText = cleanMarkdownText(textWithTokens);

  // Step 3: Block level parsing (Tables, Callouts, Headings, Lists, Paragraphs)
  const lines = cleanedText.split('\n');
  const renderedBlocks = renderContentLines(lines, 'root', tokens, false, color);

  return (
    <div className={`space-y-0.5 ${className}`}>
      {renderedBlocks}
    </div>
  );
});

LatexRenderer.displayName = 'LatexRenderer';
